// Domínio de produção ainda por definir — atualizar assim que o site tiver
// deploy/domínio real (afeta sitemap, robots, canonical e Open Graph).
export const siteUrl = "https://universodelasmascotas.vercel.app";

export const siteTitle = "Universo de las Mascotas";

export const siteDescription =
  "Consejos y guías prácticas para mejorar la salud, el bienestar y la felicidad de tu compañero.";

// URL of the branded image generated by app/opengraph-image.tsx. A page that
// declares its own `openGraph` block replaces the inherited one entirely
// (including the file-based image), so pages doing that must point back here
// explicitly or they end up with no social preview at all.
export const defaultOgImage = `${siteUrl}/opengraph-image`;
